server:
    port: 4000
 
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root
    virtual-host: /
    publisher-confirms: true  #  消息发送到交换机确认机制,是否确认回调
    publisher-returns: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #这里是配置druid连接池，以下都是druid的配置信息
    url: jdbc:mysql://localhost:3306/northpark?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    
logging:
  file: rabbitmq-service.log
  level: 
    root: info
